# Generated by Django 5.1.7 on 2025-03-29 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_studentform_delete_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentForm',
            new_name='Student',
        ),
    ]
